############################################################
# Dockerfile to build emby container image
# based on Original Emby Image
############################################################
# Container Emby Server
############################################################

# Set the base Image
FROM linuxserver/webgrabplus:latest

# File Author / Maintainer
MAINTAINER Sven Berger
