############################################################
# Dockerfile to build emby container image
# based on Original Emby Image
############################################################
# Container Emby Server
############################################################

# Set the base Image
FROM emby/embyserver:4.0.0.2

# File Author / Maintainer
MAINTAINER Sven Berger
