############################################################
# Dockerfile to build emby container image
# based on Original Emby Image
############################################################
# Container Emby Server
############################################################

# Set the base Image
FROM emby/embyserver:3.5.3.0

# File Author / Maintainer
MAINTAINER Sven Berger
