############################################################
# Dockerfile to build tvheadend container image
# based on Linuxserver TvHeadend Release Weekly Image
############################################################
# Container TvHeadend Server Server
############################################################

# Set the base Image
FROM linuxserver/tvheadend:release-4.2

# File Author / Maintainer
MAINTAINER Sven Berger
